#!/usr/bin/env php
<?php

function includeIfExists(string $file) {
  return file_exists($file) ? include $file : null;
}

if ((!$loader = includeIfExists(__DIR__ . '/vendor/autoload.php')) && (!$loader = includeIfExists(__DIR__.'/../../autoload.php'))) {
  echo 'You must set up the project dependencies using `composer install`'.PHP_EOL;
  exit(1);
}

use PhpCP\Command\ConfigCommand;
use PhpCP\Command\FileDownload;
use PhpCP\Command\RepoDeployCommand;
use PhpCP\Command\RepoListCommand;
use PhpCP\Command\RepoPullCommand;
use Symfony\Component\Console\Application;

$application = new Application('PHP CPanel cli', '0.0.1');
$application->addCommands([
  new ConfigCommand(),
  new FileDownload(),
  new RepoDeployCommand(),
  new RepoListCommand(),
  new RepoPullCommand(),
]);
$application->run();
