#!/usr/bin/env php
<?php

require __DIR__ . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

use PhpCP\Command\ConfigCommand;
use PhpCP\Command\FileDownload;
use PhpCP\Command\RepoDeployCommand;
use PhpCP\Command\RepoListCommand;
use PhpCP\Command\RepoPullCommand;
use Symfony\Component\Console\Application;

$application = new Application('PHP CPanel cli', '0.0.1');
$application->addCommands([
  new ConfigCommand(),
  new FileDownload(),
  new RepoDeployCommand(),
  new RepoListCommand(),
  new RepoPullCommand(),
]);
$application->run();
